name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 重要：确保获取完整的提交历史

      - name: Set up Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          # 删除了不支持的参数: package-name 和 changelog-types

      # 添加一个稳定标签指向最新发布版本
      - name: Tag stable version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
