name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: sapnvim_project.nvim
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"style","section":"Styling","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"test","section":"Tests","hidden":false},
              {"type":"build","section":"Build System","hidden":false},
              {"type":"ci","section":"CI","hidden":false},
              {"type":"chore","section":"Chores","hidden":false}
            ]

      # 添加一个稳定标签指向最新发布版本
      - name: Tag stable version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
